# ============================================
# ESP32 PWM Fan Controller with Temperature Control
# ============================================

esphome:
  name: fan-controller
  friendly_name: Rack Fan Controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# ============================================
# GLOBALS
# ============================================
globals:
  - id: last_fan_speed
    type: float
    restore_value: true
    initial_value: '0.0'

# ============================================
# WIFI
# ============================================
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Fan-Controller-Fallback"
    password: !secret wifi_password

mdns:

captive_portal:

# ============================================
# API + OTA
# ============================================
api:

ota:
  - platform: esphome
    password: !secret ota_password

# ============================================
# WEB SERVER
# ============================================
web_server:
  port: 80
  version: 3
  auth:
    username: !secret web_username
    password: !secret web_password

# ============================================
# LOGGING
# ============================================
logger:
  level: WARN

# ============================================
# ONE WIRE
# ============================================
one_wire:
  - platform: gpio
    pin: GPIO4

# ============================================
# SENSORS
# ============================================
sensor:
  - platform: dallas_temp
    index: 0
    name: "01 🌡 Temp TOP"
    id: temp_top
    update_interval: 5s
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1

  - platform: dallas_temp
    index: 1
    name: "02 🌡 Temp BOTTOM"
    id: temp_bottom
    update_interval: 5s
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1

  - platform: template
    name: "03 🌡 Temp MAX"
    id: temp_max
    update_interval: 5s
    lambda: |-
      float t = id(temp_top).state;
      float b = id(temp_bottom).state;
      if (isnan(t) && isnan(b)) return {};
      if (isnan(t)) return b;
      if (isnan(b)) return t;
      return max(t, b);
    on_value:
      - script.execute: auto_control_script

  - platform: wifi_signal
    name: "90 📶 WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "91 ⏱ Uptime"
    update_interval: 60s

# ============================================
# OUTPUTS (PWM)
# ============================================
output:
  - platform: ledc
    pin: GPIO25
    frequency: 25000 Hz
    id: fan_top_pwm

  - platform: ledc
    pin: GPIO26
    frequency: 25000 Hz
    id: fan_down_pwm

# ============================================
# FANS
# ============================================
fan:
  - platform: speed
    output: fan_top_pwm
    name: "40 𖣘 Fan TOP"
    id: fan_top
    restore_mode: ALWAYS_OFF

  - platform: speed
    output: fan_down_pwm
    name: "41 𖣘 Fan BOTTOM"
    id: fan_down
    restore_mode: ALWAYS_OFF

# ============================================
# SCRIPT – AUTO CONTROL WITH 3°C HYSTERESIS
# ============================================
script:
  - id: auto_control_script
    mode: restart
    then:
      - if:
          condition:
            switch.is_on: auto_control
          then:
            - lambda: |-
                float temp = id(temp_max).state;
                if (isnan(temp)) return;

                float t1 = id(temp_threshold_1).state;
                float t2 = id(temp_threshold_2).state;
                float t3 = id(temp_threshold_3).state;

                float s1 = id(fan_speed_1).state;
                float s2 = id(fan_speed_2).state;
                float s3 = id(fan_speed_3).state;

                const float H = 3.0;
                float new_speed = id(last_fan_speed);

                if (temp < (t1 - H)) new_speed = 0;
                else if (temp < (t2 - H)) new_speed = s1;
                else if (temp < (t3 - H)) new_speed = s2;
                else if (temp >= t3) new_speed = s3;

                if (new_speed != id(last_fan_speed)) {
                  id(last_fan_speed) = new_speed;

                  if (new_speed > 0) {
                    auto c1 = id(fan_top).turn_on();
                    c1.set_speed(new_speed);
                    c1.perform();

                    auto c2 = id(fan_down).turn_on();
                    c2.set_speed(new_speed);
                    c2.perform();
                  } else {
                    id(fan_top).turn_off().perform();
                    id(fan_down).turn_off().perform();
                  }
                }

# ============================================
# SWITCHES
# ============================================
switch:
  - platform: template
    name: "10 ⚙ Auto Control"
    id: auto_control
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: template
    name: "11 ⏻ Fans ON/OFF"
    id: master_switch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - fan.turn_on:
          id: fan_top
          speed: 50
      - fan.turn_on:
          id: fan_down
          speed: 50
    turn_off_action:
      - fan.turn_off: fan_top
      - fan.turn_off: fan_down

# ============================================
# NUMBERS – AUTO MODE CONFIG
# ============================================
number:
  - platform: template
    name: "20 🔥 Temp Start"
    id: temp_threshold_1
    min_value: 20
    max_value: 50
    step: 1
    initial_value: 30
    optimistic: true

  - platform: template
    name: "21 🔥 Temp Medium"
    id: temp_threshold_2
    min_value: 30
    max_value: 60
    step: 1
    initial_value: 40
    optimistic: true

  - platform: template
    name: "22 🔥 Temp High"
    id: temp_threshold_3
    min_value: 40
    max_value: 80
    step: 1
    initial_value: 50
    optimistic: true

  - platform: template
    name: "30 𖣘 Fan Speed Low"
    id: fan_speed_1
    min_value: 20
    max_value: 60
    step: 5
    initial_value: 30
    optimistic: true

  - platform: template
    name: "31 𖣘 Fan Speed Medium"
    id: fan_speed_2
    min_value: 40
    max_value: 80
    step: 5
    initial_value: 60
    optimistic: true

  - platform: template
    name: "32 𖣘 Fan Speed High"
    id: fan_speed_3
    min_value: 60
    max_value: 100
    step: 5
    initial_value: 100
    optimistic: true

# ============================================
# BUTTONS
# ============================================
button:
  - platform: restart
    name: "92 🔄 Restart Controller"

  - platform: template
    name: "93 🧪 Test Fans"
    on_press:
      - switch.turn_off: auto_control
      - fan.turn_on:
          id: fan_top
          speed: 100
      - fan.turn_on:
          id: fan_down
          speed: 100
      - delay: 5s
      - fan.turn_off: fan_top
      - fan.turn_off: fan_down

  - platform: template
    name: "99 ⛔ STOP Fans"
    on_press:
      - switch.turn_off: auto_control
      - fan.turn_off: fan_top
      - fan.turn_off: fan_down
      - switch.turn_off: master_switch
